Add Github Action to build and push docker images after each release
flightaware/firestarter pull request #21
Opened 2021-03-25 19:16 UTC by maryryang2

This will run after each release is tagged and after we merge to master.

Please squash and merge.

2021-03-26 13:24 UTC, maryryang2 commented
This passes unit tests on my fork with the secrets specified.

2021-03-30 15:58 UTC, bovine approved these changes

2021-04-09 15:31 UTC, NasaGeek requested changes
Absolutely embarrassing that it took me this long to get this reviewed. Sorry about that.

2021-04-12 14:15 UTC, NasaGeek approved these changes

2021-04-12 14:16 UTC, merged